defaults: &defaults

development:
  <<: *defaults

test:
  <<: *defaults

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter:
    comsumer_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
    comsumer_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>
